### ISSUE TITLE
Validation Error

### ISSUE THREAD

**Issue by donnielee** [jrwesolo/limits#12]
As I tested with the instructions on README.md, I experienced validation fail. Chef client version is Chef: 12.19.36. What did I wrong?

#cat recipe.rb
set_limit 'alice' do
  type 'hard'
  item 'nofile'
  value 2048
end

set_limit 'alice' do
  type 'soft'
  item 'nofile'
  value 1024
end

set_limit '*' do
  type 'hard'
  item 'nofile'
  value 4096
  use_system true
end

set_limit '*' do
  type 'soft'
  item 'nofile'
  value 1024
  use_system true
end

[root@localhost limits.d]# chef-client
[2017-03-09T08:47:41+00:00] INFO: Forking chef instance to converge...
Starting Chef Client, version 12.19.36
[2017-03-09T08:47:41+00:00] INFO: *** Chef 12.19.36 ***
[2017-03-09T08:47:41+00:00] INFO: Platform: x86_64-linux
[2017-03-09T08:47:41+00:00] INFO: Chef-client pid: 16210
[2017-03-09T08:47:44+00:00] INFO: Run List is [recipe[limits]]
[2017-03-09T08:47:44+00:00] INFO: Run List expands to [limits]
[2017-03-09T08:47:44+00:00] INFO: Starting Chef Run for node03
[2017-03-09T08:47:44+00:00] INFO: Running start handlers
[2017-03-09T08:47:44+00:00] INFO: Start handlers complete.
[2017-03-09T08:47:46+00:00] INFO: HTTP Request Returned 404 Not Found: 
[2017-03-09T08:47:46+00:00] INFO: Error while reporting run start to Data Collector. URL: https://api.chef.io/organizations/niclab/data-collector Exception: 404 -- 404 "Not Found"  (This is normal if you do not have Chef Automate)
resolving cookbooks for run list: ["limits"]
[2017-03-09T08:47:47+00:00] INFO: Loading cookbooks [limits@1.0.0]
Synchronizing Cookbooks:
[2017-03-09T08:47:50+00:00] INFO: Storing updated cookbooks/limits/recipes/default.rb in the cache.
  - limits (1.0.0)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 1 resources
Recipe: limits::default
  * limits_config[alice] action create
    
    ================================================================================
    Error executing action `create` on resource 'limits_config[alice]'
    ================================================================================
    
    Chef::Exceptions::ValidationFailed
    ----------------------------------
    Option path must be a kind of [String]!  You passed {"alice.hard.nofile"=>2048}.
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/limits/providers/config.rb:12:in `block (2 levels) in class_from_file'
    /var/chef/cache/cookbooks/limits/providers/config.rb:11:in `block in class_from_file'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/limits/definitions/default.rb
    
     24:     r = limits_config params[:filename] do
     25:       limits []
     26:       use_system params[:use_system]
     27:       action :create
     28:     end
     29:   end
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/limits/definitions/default.rb:24:in `rescue in block in from_file'
    
    limits_config("alice") do
      params {:use_system=>false, :filename=>"alice", :domain=>nil, :type=>"hard", :item=>"nofile", :value=>2048, :name=>"alice"}
      action [:create]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :limits_config
      cookbook_name "limits"
      recipe_name "default"
      limits [{:domain=>"alice", :type=>"hard", :item=>"nofile", :value=>2048}, {:domain=>"alice", :type=>"soft", :item=>"nofile", :value=>1024}]
      use_system false
      filename "alice"
    end
    
    Platform:
    ---------
    x86_64-linux
    
[2017-03-09T08:47:50+00:00] INFO: Running queued delayed notifications before re-raising exception

Running handlers:
[2017-03-09T08:47:50+00:00] ERROR: Running exception handlers
Running handlers complete
[2017-03-09T08:47:50+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 08 seconds
[2017-03-09T08:47:50+00:00] INFO: Sending resource update report (run-id: 8cce39d9-cb23-4f09-9006-c850ef319768)
[2017-03-09T08:47:51+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2017-03-09T08:47:51+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-03-09T08:47:51+00:00] ERROR: limits_config[alice] (limits::default line 24) had an error: Chef::Exceptions::ValidationFailed: Option path must be a kind of [String]!  You passed {"alice.hard.nofile"=>2048}.
[2017-03-09T08:47:51+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
[root@localhost limits.d]#

**Comment by jestallin** [comment]
#8 - The default recipes have been removed in favor of a LWRP. Based on the README this isn't clear enough.
